[package]
name = "advent-2020"
version = "0.1.0"
authors = ["John Downey <jdowney@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.14.0"
num-integer = "0.1.46"
pest = "2"
pest_derive = "2"
regex = "1"
