[package]
name = "advent-2024"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.14.0"
rayon = "1.11.0"
regex = "1.11.1"
