[package]
name = "advent-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"
