[package]
name = "advent-2022"
version = "0.1.0"
edition = "2024"

[dependencies]
advent-of-code-ocr = "0.1.1"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
anyhow = "1.0"
itertools = "0.14.0"
nom = { version = "8", features = ["alloc"] }
num = "0.4"
smallvec = "1.15.1"
take-until = "0.2.0"
