[package]
name = "advent-2016"
version = "0.1.0"
edition = "2024"

[dependencies]
advent-of-code-ocr = "0.1.1"
anyhow = "1.0.99"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.14.0"
md5 = "0.8.0"
nom = "8"
regex = "1.11.1"
